name: test

on:
  pull_request:
  push:
      branches:
      - main

jobs:
  mix_test:
    name: mix test (OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})

    env:
      MIX_ENV: test

    strategy:
      matrix:
        include:
          - elixir: 1.18.1
            otp: 27.1
            lint: true
            installer: true


    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v4
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}

    - name: Install Dependencies
      run: mix deps.get --only test

    - name: Run Tests
      run: mix test
